databases:
  - name: rentapp-db
    plan: free
    databaseName: rentapp
    user: rentapp

services:
  - type: web
    name: roomfinder-api
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        fromDatabase:
          name: rentapp-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: rentapp-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: rentapp-db
          property: password
